// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Transaction struct {
	ID            string
	WalletID      string
	Amount        int32
	OperationType string
	CreatedAt     time.Time
}

type Wallet struct {
	ID        string
	Amount    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
